PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE TEXT,
APELLIDO TEXT,
EMAIL TEXT UNIQUE,
ACTIVADO TEXT,
PASSWORD TEXT DEFAULT 'Y'
);

DROP TABLE IF EXISTS ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR (
ID_ADMINISTRADOR INTEGER PRIMARY KEY,
FEC_ULTIMA_CONEX TEXT,
FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES USUARIO(ID_USUARIO)  
ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS INVITADO;
CREATE TABLE INVITADO (
ID_INVITADO INTEGER PRIMARY KEY,
FEC_ULTIMA_CONEX TEXT,
FOREIGN KEY (ID_INVITADO) REFERENCES USUARIO(ID_USUARIO)  
ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS REGISTRADO;
CREATE TABLE REGISTRADO (
ID_REGISTRADO INTEGER PRIMARY KEY,
NICK TEXT,
FOREIGN KEY (ID_REGISTRADO) REFERENCES USUARIO(ID_USUARIO)  
ON UPDATE CASCADE ON DELETE CASCADE 
);

DROP VIEW IF EXISTS VISTA_ADMINISTRADOR;
CREATE VIEW VISTA_ADMINISTRADOR AS SELECT A.ID_ADMINISTRADOR, U.NOMBRE, U.APELLIDO, U.EMAIL, 
U.PASSWORD, A.FEC_ULTIMA_CONEX FROM USUARIO U, ADMINISTRADOR A WHERE U.ID_USUARIO=A.ID_ADMINISTRADOR;

DROP VIEW IF EXISTS VISTA_REGISTRADO;
CREATE VIEW VISTA_REGISTRADO AS SELECT R.ID_REGISTRADO, U.NOMBRE, U.APELLIDO, U.EMAIL, 
 U.PASSWORD, R.NICK FROM USUARIO U, REGISTRADO R WHERE U.ID_USUARIO=R.ID_REGISTRADO;

DROP VIEW IF EXISTS VISTA_INVITADO;
CREATE VIEW VISTA_INVITADO AS SELECT I.ID_INVITADO, U.NOMBRE, U.APELLIDO, U.EMAIL, 
U.ACTIVADO, U.PASSWORD, I.FEC_ULTIMA_CONEX FROM USUARIO U, INVITADO I WHERE U.ID_USUARIO=I.ID_INVITADO;
 
DROP TABLE IF EXISTS LIBRETA;
CREATE TABLE LIBRETA (
ID_LIBRETA INTEGER PRIMARY KEY AUTOINCREMENT,
ID_REGISTRADO_LIBRETA INTEGER,
NOMBRE TEXT UNIQUE,
FOREIGN KEY (ID_REGISTRADO_LIBRETA) REFERENCES REGISTRADO(ID_REGISTRADO)  
ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS CONTACTO;
CREATE TABLE CONTACTO (
ID_CONTACTO INTEGER PRIMARY KEY AUTOINCREMENT,
NOMBRE TEXT,
APELLIDO TEXT,
EMAIL TEXT UNIQUE,
DIRECCION TEXT,
TELEFONO TEXT,
ID_LIBRETA_CONTACTO INTEGER,
FOREIGN KEY (ID_LIBRETA_CONTACTO) REFERENCES LIBRETA(ID_LIBRETA)  
ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS NOTA;
CREATE TABLE NOTA (
ID_NOTA INTEGER PRIMARY KEY AUTOINCREMENT,
ID_USUARIO_NOTA INTEGER,
ASUNTO TEXT,
DESCRIPCION TEXT,
FEC_CREACION TEXT,
FEC_MODIFICACION TEXT,
FOREIGN KEY (ID_USUARIO_NOTA) REFERENCES USUARIO(ID_USUARIO)  
ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO USUARIO(NOMBRE,APELLIDO,EMAIL,PASSWORD) VALUES ('guest','guest','invitado@guest.es',null);
INSERT INTO INVITADO VALUES ((SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='invitado@guest.es'),null);
INSERT INTO USUARIO(NOMBRE,APELLIDO,EMAIL,PASSWORD) VALUES ('admin','admin','admin@admin.es','admin');
INSERT INTO ADMINISTRADOR VALUES ((SELECT ID_USUARIO FROM USUARIO WHERE EMAIL='admin@admin.es'),null);
COMMIT;
